server:
  port: 8102

info:
  description: 用户管理

spring:
  application:
    name: user-manager
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/tuacydev?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    # 单机模式
    host: 127.0.0.1 #哨兵模式下不用配置
    port: 6379 # 哨兵模式下不用配置
    jedis:
      pool:
        #最大连接数
        max-active: 1024
        #最大阻塞等待时间(负数表示没限制)
        max-wait: 20000
        #最大空闲
        max-idle: 200
        #最小空闲
        min-idle: 10

security:
  oauth2:
    resource:
      user-info-uri: http://127.0.0.1:8000/security-service/auth/user

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5

feign:
  hystrix:
    enabled: true

hystrix:
  command:
    default: #default全局有效，service id指定应用有效
      execution:
        timeout:
          enabled: true #如果enabled设置为false，则请求超时交给ribbon控制,为true,则超时作为熔断根据
        isolation:
          thread:
            timeoutInMilliseconds: 126000 #断路器超时时间，默认1000ms
ribbon:
  MaxAutoRetries: 1 #最大重试次数，当Eureka中可以找到服务，但是服务连不上时将会重试
  MaxAutoRetriesNextServer: 1 #切换实例的重试次数
  OkToRetryOnAllOperations: true # 对所有的操作请求都进行重试，如果是get则可以，如果是post,put等操作没有实现幂等的情况下是很危险的
  ConnectTimeout: 250 #请求连接的超时时间
  ReadTimeout: 1000 #请求处理的超时时间

mybatis:
  typeAliasesPackage: com.tuacy.usermanager.entity.model
  mapperLocations: classpath:mapper/*.xml

# 配置认证服务器对应的地址
auth-service-url: http://127.0.0.1:8000/security-service
